//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualMind.TechnicalEvaluation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUD_dSectores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUD_dSectores()
        {
            this.AUD_dContenedores = new HashSet<AUD_dContenedores>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUD_dContenedores> AUD_dContenedores { get; set; }
    }
}
