//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualMind.TechnicalEvaluation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUD_dIncidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUD_dIncidencias()
        {
            this.AUD_dContenedores = new HashSet<AUD_dContenedores>();
            this.AUD_dPosiciones = new HashSet<AUD_dPosiciones>();
            this.AUD_dLimpieza = new HashSet<AUD_dLimpieza>();
        }
    
        public int id { get; set; }
        public Nullable<int> idTipoAuditoria { get; set; }
        public string incidencia { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUD_dContenedores> AUD_dContenedores { get; set; }
        public virtual AUD_sTiposAuditoria AUD_sTiposAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUD_dPosiciones> AUD_dPosiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUD_dLimpieza> AUD_dLimpieza { get; set; }
    }
}
