//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualMind.TechnicalEvaluation.Dal
{
    using System;
    
    public partial class DatosVolumetricos
    {
        public string Articulo { get; set; }
        public string PosicionPicking { get; set; }
        public string Unidad { get; set; }
        public string Caja { get; set; }
        public string UMD { get; set; }
        public decimal UxB { get; set; }
        public decimal CxH { get; set; }
        public decimal HxP { get; set; }
    }
}
