//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualMind.TechnicalEvaluation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public string amount { get; set; }
        public string isoCurrency { get; set; }
        public string price { get; set; }
        public System.DateTime ts { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
    }
}
